# Generated by Django 5.0.4 on 2024-04-26 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Наименование')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Продавец')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='Почта')),
                ('full_name', models.CharField(blank=True, max_length=256, verbose_name='Имя')),
                ('is_confirmed', models.BooleanField(blank=True, default=False, verbose_name='Подтверждено')),
                ('verify_code', models.CharField(blank=True, max_length=6, verbose_name='Код подтверждения')),
                ('code_timeout', models.CharField(blank=True, max_length=32, verbose_name='Таймаут отправки кода')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('categories', models.ManyToManyField(blank=True, to='backend.category', verbose_name='Категории')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка')),
                ('text', models.TextField(max_length=4096, verbose_name='Текст отзыва')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_review', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
