# Generated by Django 5.0.4 on 2024-04-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_advertisement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='identity',
            field=models.CharField(max_length=32, null=True, verbose_name='Идентификатор'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_data_sent',
            field=models.BooleanField(default=False, verbose_name='Текстовые данные отправлены'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='is_photo_sent',
            field=models.BooleanField(default=False, verbose_name='Фото отправлено'),
        ),
    ]
