# Generated by Django 5.0.4 on 2024-04-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_advertisement_identity_advertisement_is_data_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Объявление открыто'),
        ),
    ]
