# Generated by Django 5.0.4 on 2024-04-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_advertisement_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='num_photos',
            field=models.IntegerField(null=True, verbose_name='Количество загруженных фото'),
        ),
    ]
