# Generated by Django 5.0.4 on 2024-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_advertisement_num_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='num_photos',
            field=models.IntegerField(default=0, verbose_name='Количество загруженных фото'),
        ),
    ]
