# Generated by Django 5.0.4 on 2024-04-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_advertisement_num_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя'),
        ),
    ]
