# Generated by Django 5.0.4 on 2024-04-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_avatar',
            field=models.BooleanField(default=False, verbose_name='Есть аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
