# Generated by Django 5.0.4 on 2024-05-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_profile_is_avatar_alter_profile_is_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='identity',
            field=models.CharField(max_length=32, null=True, verbose_name='Идентификатор'),
        ),
    ]
