# Generated by Django 5.0.4 on 2024-05-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_review_reviewer_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошло модерацию'),
        ),
    ]
